
name: deploy website
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    
  
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        run: yarn

    - name: Install dependencies
      run: |
        git clone https://github.com/threefoldtech/grid_weblets.git
        cd grid_weblets
        yarn install
        cd playground && yarn install
        pwd
        cd ..
        yarn build:app


    - name: deploying website on production server 
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        passphrase: ${{ secrets.PROD_SSH_KEY_PASSPHRASE }}
        rm: false
        port: ${{ secrets.PORT }}
        source: "grid_weblets/dist/build/elements/farmingcalculator.wc.js"
        target: "${{ secrets.PROD_DIR }}"
        strip_components: 4
